# Generated by Django 3.0.4 on 2020-07-08 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=32, verbose_name='Post Title')),
                ('post_details', models.CharField(max_length=255, verbose_name='Post Details')),
                ('post_email', models.EmailField(max_length=32, unique=True, verbose_name='Contact email address')),
                ('added_date_time', models.DateTimeField(auto_now_add=True)),
                ('post_posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fast_post_user_related', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
