# Generated by Django 3.0.4 on 2020-07-08 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fast', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_email',
        ),
    ]
